/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lwrTiPiNjLQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function SwapPage() {
  return (
    <div className="max-w-4xl mx-auto p-4">
      <header className="flex justify-between items-center border-b pb-2">
        <h1 className="text-xl font-bold">FaceSwap AI</h1>
        <div className="flex items-center space-x-2">
          <span>username</span>
          <Avatar>
            <AvatarImage alt="user avatar" src="/placeholder.svg?height=32&width=32" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <main className="mt-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="border-dashed border-2 border-gray-400 rounded-lg p-4 flex flex-col items-center text-sm">
            Drag and drop or click to upload
            <img
              alt="Placeholder Image"
              className="object-cover rounded-lg mt-4"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200}
            />
          </div>
          <div className="border-dashed border-2 border-gray-400 rounded-lg p-4 flex flex-col items-center text-sm">
            Drag and drop or click to upload
            <img
              alt="Placeholder Image"
              className="object-cover rounded-lg mt-4"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200}
            />
          </div>
        </div>
        <div className="flex justify-center mt-4">
          <Button className="w-32">Submit</Button>
        </div>
      </main>
    </div>
  )
}
